DISCIPLINA: **Data Science**

DOCENTE: **Prof. Msc. Arthur Schneider Figueira**


---

GRUPO 10

DISCENTES:

Gabriel Lira de Jesus

Igor Santiago Macedo

Lucimara de Assis Leoncio

Quezia oliveira Silva

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import pandas as pd


print(tf.config.list_physical_devices('GPU'))

[]

In [ ]:
# Caminhos para os diretórios de dados
train_dir = '/content/drive/MyDrive/Data Science/Bases/Imagens/Dogs_and_Cats_10kImages/dataset/training_set'
validation_dir = '/content/drive/MyDrive/Data Science/Bases/Imagens/Dogs_and_Cats_10kImages/dataset/test_set'

In [ ]:
#Visto que há pouca amostra, vamos usar o ImageDataGenerator para ampliar a amostragem

# Pré-processamento e aumento de dados
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

validation_datagen = ImageDataGenerator(rescale=1.0/255)

In [ ]:
# Carregando imagens do diretório e aplicando o pré-processamento
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary'
)

validation_generator = validation_datagen.flow_from_directory(
    validation_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary'
)

Found 8000 images belonging to 2 classes.
Found 2000 images belonging to 2 classes.

GUARDANDO RESULTADOS

In [ ]:
resultados = []

MODELOS

In [ ]:
# CNN 1

model = tf.keras.models.Sequential([

    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(512, activation='relu'),

    tf.keras.layers.Dense(1, activation='sigmoid')

])

model.compile(loss='binary_crossentropy',
              optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.001),
              metrics=['accuracy'])

history = model.fit(
    train_generator,
    steps_per_epoch=100,
    epochs=5,
    validation_data=validation_generator,
    validation_steps=50
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 389s 3s/step - accuracy: 0.5003 - loss: 0.8722 - val_accuracy: 0.6056 - val_loss: 0.6927
Epoch 2/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 322s 3s/step - accuracy: 0.5272 - loss: 0.6931 - val_accuracy: 0.6194 - val_loss: 0.6711
Epoch 3/5
 50/100 ━━━━━━━━━━━━━━━━━━━━ 2:30 3s/step - accuracy: 0.5646 - loss: 0.6835

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/epoch_iterator.py:116: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

100/100 ━━━━━━━━━━━━━━━━━━━━ 187s 2s/step - accuracy: 0.5569 - loss: 0.6807 - val_accuracy: 0.6244 - val_loss: 0.6567
Epoch 4/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 384s 4s/step - accuracy: 0.5844 - loss: 0.6667 - val_accuracy: 0.6656 - val_loss: 0.6191
Epoch 5/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 320s 3s/step - accuracy: 0.6162 - loss: 0.6491 - val_accuracy: 0.6656 - val_loss: 0.6041

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_3 (Conv2D)               │ (None, 222, 222, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 111, 111, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 109, 109, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 54, 54, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 52, 52, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 26, 26, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 86528)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 512)            │    44,302,848 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │           513 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88,793,220 (338.72 MB)

 Trainable params: 44,396,609 (169.36 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 44,396,611 (169.36 MB)

In [ ]:
resultados.append({
    'modelo': 'CNN 1',
    'otimizador': 'RMSprop',
    'lr': 0.001,
    'val_accuracy': history.history['val_accuracy'][-1]
})

In [ ]:
# CNN 2

model = tf.keras.models.Sequential([

    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(512, activation='relu'),

    tf.keras.layers.Dense(1, activation='sigmoid')

])

model.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.0001),
    metrics=['accuracy']
)

history = model.fit(
    train_generator,
    steps_per_epoch=100,
    epochs=5,
    validation_data=validation_generator,
    validation_steps=50
)

Epoch 1/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 315s 3s/step - accuracy: 0.5225 - loss: 0.7080 - val_accuracy: 0.5956 - val_loss: 0.6756
Epoch 2/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 322s 3s/step - accuracy: 0.5694 - loss: 0.6756 - val_accuracy: 0.5881 - val_loss: 0.6564
Epoch 3/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 175s 2s/step - accuracy: 0.5400 - loss: 0.6727 - val_accuracy: 0.5769 - val_loss: 0.6566
Epoch 4/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 322s 3s/step - accuracy: 0.5894 - loss: 0.6653 - val_accuracy: 0.6212 - val_loss: 0.6423
Epoch 5/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 312s 3s/step - accuracy: 0.6025 - loss: 0.6562 - val_accuracy: 0.6419 - val_loss: 0.6296

In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_6 (Conv2D)               │ (None, 222, 222, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_6 (MaxPooling2D)  │ (None, 111, 111, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 109, 109, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_7 (MaxPooling2D)  │ (None, 54, 54, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 52, 52, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_8 (MaxPooling2D)  │ (None, 26, 26, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 86528)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 512)            │    44,302,848 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │           513 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88,793,220 (338.72 MB)

 Trainable params: 44,396,609 (169.36 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 44,396,611 (169.36 MB)

In [ ]:
resultados.append({
    'modelo': 'CNN 2',
    'otimizador': 'RMSprop',
    'lr': 0.0001,
    'val_accuracy': history.history['val_accuracy'][-1]
})

In [ ]:
# CNN 3

model = tf.keras.models.Sequential([

    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(512, activation='relu'),

    tf.keras.layers.Dense(1, activation='sigmoid')

])

model.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy']
)

history = model.fit(
    train_generator,
    steps_per_epoch=100,
    epochs=5,
    validation_data=validation_generator,
    validation_steps=50
)

Epoch 1/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 313s 3s/step - accuracy: 0.5059 - loss: 0.8803 - val_accuracy: 0.5725 - val_loss: 0.6903
Epoch 2/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 382s 4s/step - accuracy: 0.5525 - loss: 0.6887 - val_accuracy: 0.5694 - val_loss: 0.6806
Epoch 3/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 180s 2s/step - accuracy: 0.5506 - loss: 0.6868 - val_accuracy: 0.5700 - val_loss: 0.6768
Epoch 4/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 436s 4s/step - accuracy: 0.5619 - loss: 0.6837 - val_accuracy: 0.5750 - val_loss: 0.6753
Epoch 5/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 384s 4s/step - accuracy: 0.5697 - loss: 0.6845 - val_accuracy: 0.5731 - val_loss: 0.6798

In [ ]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_9 (Conv2D)               │ (None, 222, 222, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_9 (MaxPooling2D)  │ (None, 111, 111, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_10 (Conv2D)              │ (None, 109, 109, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_10 (MaxPooling2D) │ (None, 54, 54, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_11 (Conv2D)              │ (None, 52, 52, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_11 (MaxPooling2D) │ (None, 26, 26, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 86528)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 512)            │    44,302,848 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │           513 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 133,189,829 (508.08 MB)

 Trainable params: 44,396,609 (169.36 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 88,793,220 (338.72 MB)

In [ ]:
resultados.append({
    'modelo': 'CNN 3',
    'otimizador': 'Adam',
    'lr': 0.001,
    'val_accuracy': history.history['val_accuracy'][-1]
})

In [ ]:
# CNN 4

model = tf.keras.models.Sequential([

    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),

    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(512, activation='relu'),

    tf.keras.layers.Dense(1, activation='sigmoid')

])

model.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    metrics=['accuracy']
)

history = model.fit(
    train_generator,
    steps_per_epoch=100,
    epochs=5,
    validation_data=validation_generator,
    validation_steps=50
)

Epoch 1/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 398s 4s/step - accuracy: 0.5472 - loss: 0.6878 - val_accuracy: 0.5487 - val_loss: 0.6726
Epoch 2/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 440s 4s/step - accuracy: 0.5944 - loss: 0.6551 - val_accuracy: 0.6250 - val_loss: 0.6385
Epoch 3/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 223s 2s/step - accuracy: 0.6237 - loss: 0.6350 - val_accuracy: 0.6237 - val_loss: 0.6467
Epoch 4/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 383s 4s/step - accuracy: 0.6391 - loss: 0.6294 - val_accuracy: 0.6125 - val_loss: 0.6492
Epoch 5/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 395s 4s/step - accuracy: 0.6559 - loss: 0.6210 - val_accuracy: 0.6494 - val_loss: 0.6035

In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)              │ (None, 222, 222, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_12 (MaxPooling2D) │ (None, 111, 111, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_13 (Conv2D)              │ (None, 109, 109, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_13 (MaxPooling2D) │ (None, 54, 54, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_14 (Conv2D)              │ (None, 52, 52, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_14 (MaxPooling2D) │ (None, 26, 26, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 86528)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 512)            │    44,302,848 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │           513 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 133,189,829 (508.08 MB)

 Trainable params: 44,396,609 (169.36 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 88,793,220 (338.72 MB)

In [ ]:
resultados.append({
    'modelo': 'CNN 4',
    'otimizador': 'Adam',
    'lr': 0.0001,
    'val_accuracy': history.history['val_accuracy'][-1]
})

RESULTADOS CNN

In [ ]:

df = pd.DataFrame(resultados)
df

  modelo otimizador      lr  val_accuracy
0  CNN 1    RMSprop  0.0010      0.665625
1  CNN 2    RMSprop  0.0001      0.641875
2  CNN 3       Adam  0.0010      0.573125
3  CNN 4       Adam  0.0001      0.649375

In [ ]:
df.sort_values(by='val_accuracy', ascending=False)

  modelo otimizador      lr  val_accuracy
0  CNN 1    RMSprop  0.0010      0.665625
3  CNN 4       Adam  0.0001      0.649375
1  CNN 2    RMSprop  0.0001      0.641875
2  CNN 3       Adam  0.0010      0.573125

In [ ]:
MobileNetV2 = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3),
                                               include_top=False,
                                               weights='imagenet')

MobileNetV2.trainable = False

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5
9406464/9406464 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step

In [ ]:
model_TransferLearning_MobileNetV2 = tf.keras.Sequential([
    MobileNetV2,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [ ]:
# Transfer Learning 1

model_TransferLearning_MobileNetV2.compile(loss='binary_crossentropy',
              optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.001),
              metrics=['accuracy'])

# Treinamento do modelo
history_MobileNetV2 = model_TransferLearning_MobileNetV2.fit(
    train_generator,
    steps_per_epoch=100,
    epochs=5,
    validation_data=validation_generator,
    validation_steps=50
)

Epoch 1/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 166s 2s/step - accuracy: 0.9653 - loss: 0.0801 - val_accuracy: 0.9812 - val_loss: 0.0672
Epoch 2/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 201s 2s/step - accuracy: 0.9722 - loss: 0.0762 - val_accuracy: 0.9831 - val_loss: 0.0542
Epoch 3/5
 50/100 ━━━━━━━━━━━━━━━━━━━━ 55s 1s/step - accuracy: 0.9778 - loss: 0.0601

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/epoch_iterator.py:116: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

100/100 ━━━━━━━━━━━━━━━━━━━━ 100s 998ms/step - accuracy: 0.9787 - loss: 0.0659 - val_accuracy: 0.9881 - val_loss: 0.0446
Epoch 4/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 159s 2s/step - accuracy: 0.9678 - loss: 0.0791 - val_accuracy: 0.9837 - val_loss: 0.0498
Epoch 5/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 156s 2s/step - accuracy: 0.9694 - loss: 0.0806 - val_accuracy: 0.9800 - val_loss: 0.0432

In [ ]:
model_TransferLearning_MobileNetV2.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ mobilenetv2_1.00_224            │ (None, 7, 7, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 128)            │       163,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,586,180 (9.87 MB)

 Trainable params: 164,097 (641.00 KB)

 Non-trainable params: 2,257,984 (8.61 MB)

 Optimizer params: 164,099 (641.02 KB)

In [ ]:
resultados.append({
    'modelo': 'MobileNetV2 Freeze',
    'tipo': 'Transfer Learning',
    'val_accuracy': history_MobileNetV2.history['val_accuracy'][-1]
})

In [ ]:
MobileNetV2 = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3),
                                               include_top=False,
                                               weights='imagenet')

MobileNetV2.trainable = True

In [ ]:
model1_TransferLearning_MobileNetV2 = tf.keras.Sequential([
    MobileNetV2,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [ ]:
# Transfer Learning 2

model1_TransferLearning_MobileNetV2.compile(loss='binary_crossentropy',
              optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.001),
              metrics=['accuracy'])

history2_MobileNetV2 = model1_TransferLearning_MobileNetV2.fit(
    train_generator,
    steps_per_epoch=100,
    epochs=5,
    validation_data=validation_generator,
    validation_steps=50
)

Epoch 1/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 448s 4s/step - accuracy: 0.9391 - loss: 0.1718 - val_accuracy: 0.5038 - val_loss: 10.0763
Epoch 2/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 445s 4s/step - accuracy: 0.9422 - loss: 0.1487 - val_accuracy: 0.7669 - val_loss: 1.2437
Epoch 3/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 245s 2s/step - accuracy: 0.9488 - loss: 0.1298 - val_accuracy: 0.7894 - val_loss: 0.9905
Epoch 4/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 442s 4s/step - accuracy: 0.9453 - loss: 0.1365 - val_accuracy: 0.7506 - val_loss: 1.6196
Epoch 5/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 443s 4s/step - accuracy: 0.9450 - loss: 0.1360 - val_accuracy: 0.7219 - val_loss: 1.8362

In [ ]:
model1_TransferLearning_MobileNetV2.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ mobilenetv2_1.00_224            │ (None, 7, 7, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d_1      │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 128)            │       163,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,810,052 (18.35 MB)

 Trainable params: 2,387,969 (9.11 MB)

 Non-trainable params: 34,112 (133.25 KB)

 Optimizer params: 2,387,971 (9.11 MB)

In [ ]:
resultados.append({
    'modelo': 'MobileNetV2 Fine-Tuning',
    'tipo': 'Transfer Learning',
    'val_accuracy': history2_MobileNetV2.history['val_accuracy'][-1]
})

In [ ]:
VGG16_base = tf.keras.applications.VGG16(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)

VGG16_base.trainable = False

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5
58889256/58889256 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step

In [ ]:
model2_TransferLearning_VGG16 = tf.keras.Sequential([
    VGG16_base,
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [ ]:
# Transfer Learning 3

model2_TransferLearning_VGG16.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy']
)

history3_VGG16 = model2_TransferLearning_VGG16.fit(
    train_generator,
    steps_per_epoch=100,
    epochs=5,
    validation_data=validation_generator,
    validation_steps=50
)

Epoch 1/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 2954s 29s/step - accuracy: 0.7644 - loss: 0.5912 - val_accuracy: 0.8950 - val_loss: 0.2511
Epoch 2/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 2888s 29s/step - accuracy: 0.8375 - loss: 0.3673 - val_accuracy: 0.8894 - val_loss: 0.2520
Epoch 3/5
 50/100 ━━━━━━━━━━━━━━━━━━━━ 16:06 19s/step - accuracy: 0.8683 - loss: 0.3089

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/epoch_iterator.py:116: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

100/100 ━━━━━━━━━━━━━━━━━━━━ 1939s 19s/step - accuracy: 0.8619 - loss: 0.3054 - val_accuracy: 0.9044 - val_loss: 0.2146
Epoch 4/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 2888s 29s/step - accuracy: 0.8731 - loss: 0.2956 - val_accuracy: 0.9000 - val_loss: 0.2256
Epoch 5/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 2827s 28s/step - accuracy: 0.8769 - loss: 0.2898 - val_accuracy: 0.9106 - val_loss: 0.2169

In [ ]:
model2_TransferLearning_VGG16.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ vgg16 (Functional)              │ (None, 7, 7, 512)      │    14,714,688 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │     3,211,392 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 24,349,253 (92.89 MB)

 Trainable params: 3,211,521 (12.25 MB)

 Non-trainable params: 14,714,688 (56.13 MB)

 Optimizer params: 6,423,044 (24.50 MB)

In [ ]:
resultados.append({
    'modelo': 'VGG16 Freeze',
    'tipo': 'Transfer Learning',
    'val_accuracy': history3_VGG16.history['val_accuracy'][-1]
})

In [ ]:
VGG16_base = tf.keras.applications.VGG16(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)

VGG16_base.trainable = True

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5
58889256/58889256 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step

In [ ]:
model3_TransferLearning_VGG16 = tf.keras.Sequential([
    VGG16_base,
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [ ]:
# Transfer Learning 4

model3_TransferLearning_VGG16.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    metrics=['accuracy']
)

history4_VGG16 = model3_TransferLearning_VGG16.fit(
    train_generator,
    steps_per_epoch=100,
    epochs=5,
    validation_data=validation_generator,
    validation_steps=50
)

Epoch 1/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 6259s 61s/step - accuracy: 0.7956 - loss: 0.4256 - val_accuracy: 0.9119 - val_loss: 0.1990
Epoch 2/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 5397s 54s/step - accuracy: 0.9091 - loss: 0.2067 - val_accuracy: 0.9569 - val_loss: 0.1095
Epoch 3/5
 50/100 ━━━━━━━━━━━━━━━━━━━━ 39:06 47s/step - accuracy: 0.9371 - loss: 0.1661

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/epoch_iterator.py:116: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

100/100 ━━━━━━━━━━━━━━━━━━━━ 3072s 31s/step - accuracy: 0.9350 - loss: 0.1648 - val_accuracy: 0.9594 - val_loss: 0.1010
Epoch 4/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 5373s 54s/step - accuracy: 0.9403 - loss: 0.1418 - val_accuracy: 0.9688 - val_loss: 0.0911
Epoch 5/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 5425s 54s/step - accuracy: 0.9344 - loss: 0.1552 - val_accuracy: 0.9531 - val_loss: 0.1522

In [ ]:
model3_TransferLearning_VGG16.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ vgg16 (Functional)              │ (None, 7, 7, 512)      │    14,714,688 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │     3,211,392 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 53,778,629 (205.15 MB)

 Trainable params: 17,926,209 (68.38 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 35,852,420 (136.77 MB)

In [ ]:
resultados.append({
    'modelo': 'VGG16 Fine-Tuning',
    'tipo': 'Transfer Learning',
    'val_accuracy': history4_VGG16.history['val_accuracy'][-1]
})

NameError: name 'resultados' is not defined

In [ ]:
df = pd.DataFrame(resultados)
df.sort_values(by='val_accuracy', ascending=False)